trigger AccountUpdateTempTrigger on Account (before update){
  if(FeatureManagement.checkPermission('ETL_PreventOverwrite')){
    for(Account a:trigger.new){
      Account oldAcc=trigger.oldMap.get(a.Id);
      if(oldAcc.accountnumber!=null){
        a.accountnumber=oldAcc.accountnumber;
      }
      if(oldAcc.accountsource!=null){
        a.accountsource=oldAcc.accountsource;
      }
      if(oldAcc.annualrevenue!=null){
        a.annualrevenue=oldAcc.annualrevenue;
      }
      if(oldAcc.BillingStreet!=null && oldAcc.BillingStreet!=a.BillingStreet){
				a.BillingStreet=oldAcc.BillingStreet;
				a.BillingCity=oldAcc.BillingCity;
				a.BillingState=oldAcc.BillingState;
				a.BillingPostalCode=oldAcc.BillingPostalCode;
				a.BillingCountry=oldAcc.BillingCountry;
				a.BillingLatitude=oldAcc.BillingLatitude;
				a.BillingLongitude=oldAcc.BillingLongitude;
        a.billinggeocodeaccuracy=oldAcc.billinggeocodeaccuracy;
			}
      if(oldAcc.Branches__c!=null){
        a.Branches__c=oldAcc.Branches__c;
      }
      if(oldAcc.CDM_Sub_Account_Type__c!=null){
        a.CDM_Sub_Account_Type__c=oldAcc.CDM_Sub_Account_Type__c;
      }
      if(oldAcc.currencyisocode!=null){
        a.currencyisocode=oldAcc.currencyisocode;
      }
      if(oldAcc.description!=null){
        a.description=oldAcc.description;
      }
      if(oldAcc.fax!=null){
        a.fax=oldAcc.fax;
      }
      if(oldAcc.FDIC__c!=null){
        a.FDIC__c=oldAcc.FDIC__c;
      }
      if(oldAcc.industry !=null){
        a.industry =oldAcc.industry ;
      }
      if(oldAcc.isexcludedfromrealign!=null){
        a.isexcludedfromrealign=oldAcc.isexcludedfromrealign;
      }
      if(oldAcc.jigsaw!=null){
        a.jigsaw=oldAcc.jigsaw;
      }
      if(oldAcc.name!=null){
        a.name=oldAcc.name;
      }
      if(oldAcc.NCUA__c!=null){
        a.NCUA__c=oldAcc.NCUA__c;
      }
      if(oldAcc.No_of_ATM_S__c!=null){
        a.No_of_ATM_S__c=oldAcc.No_of_ATM_S__c;
      }
      if(oldAcc.numberofemployees!=null){
        a.numberofemployees=oldAcc.numberofemployees;
      }
      if(oldAcc.ownership!=null){
        a.ownership=oldAcc.ownership;
      }
      if(oldAcc.phone!=null){
        a.phone=oldAcc.phone;
      }
      if(oldAcc.rating!=null){
        a.rating=oldAcc.rating;
      }
      if(oldAcc.ShippingStreet!=null && oldAcc.ShippingStreet!=a.ShippingStreet){
				a.ShippingStreet=oldAcc.ShippingStreet;
				a.ShippingCity=oldAcc.ShippingCity;
				a.ShippingState=oldAcc.ShippingState;
				a.ShippingPostalCode=oldAcc.ShippingPostalCode;
				a.ShippingCountry=oldAcc.ShippingCountry;
				a.ShippingLatitude=oldAcc.ShippingLatitude;
				a.ShippingLongitude=oldAcc.ShippingLongitude;
        a.Shippinggeocodeaccuracy=oldAcc.Shippinggeocodeaccuracy;
			}
      if(oldAcc.sic!=null){
        a.sic=oldAcc.sic;
      }   
      if(oldAcc.sicdesc!=null){
        a.sicdesc=oldAcc.sicdesc;
      }   
      if(oldAcc.site!=null){
        a.site=oldAcc.site;
      }   
      if(oldAcc.tickersymbol!=null){
        a.tickersymbol=oldAcc.tickersymbol;
      }   
      if(oldAcc.type!=null){
        a.type=oldAcc.type;
      }   
      if(oldAcc.website!=null){
        a.website=oldAcc.website;
      }
    }
  }
}