trigger ContactUpdateTempTrigger on Contact (before update){
  if(FeatureManagement.checkPermission('ETL_PreventOverwrite')){
    for(Contact c:trigger.new){
      Contact oc=trigger.oldMap.get(c.Id);
      if(oc.Active_Contact__c!=null){
        c.Active_Contact__c=oc.Active_Contact__c;
      }
      if(oc.assistantname!=null){
        c.assistantname=oc.assistantname;
      }
      if(oc.assistantphone!=null){
        c.assistantphone=oc.assistantphone;
      }
      if(oc.currencyisocode!=null){
        c.currencyisocode=oc.currencyisocode;
      }
      if(oc.department!=null){
        c.department=oc.department;
      }
      if(oc.description!=null){
        c.description=oc.description;
      }
      if(oc.Email!=null){
        c.Email=oc.Email;
      }
      if(oc.emailbounceddate!=null){
        c.emailbounceddate=oc.emailbounceddate;
      }
      if(oc.emailbouncedreason!=null){
        c.emailbouncedreason=oc.emailbouncedreason;
      }
      if(oc.fax!=null){
        c.fax=oc.fax;
      }
      if(oc.firstname!=null){
        c.firstname=oc.firstname;
      }
      if(oc.hasoptedoutofemail!=null){
        c.hasoptedoutofemail=oc.hasoptedoutofemail;
      }
      if(oc.hasoptedoutoffax!=null){
        c.hasoptedoutoffax=oc.hasoptedoutoffax;
      }
      if(oc.homephone!=null){
        c.homephone=oc.homephone;
      }
      if(oc.jigsaw!=null){
        c.jigsaw=oc.jigsaw;
      }
      if(oc.lastname!=null){
        c.lastname=oc.lastname;
      }
      if(oc.leadsource!=null){
        c.leadsource=oc.leadsource;
      }
      if(oc.Level__c!=null){
        c.Level__c=oc.Level__c;
      }   
      if(oc.Linkedin_URL__c!=null){
        c.Linkedin_URL__c=oc.Linkedin_URL__c;
      }
			if(oc.MailingStreet!=null && oc.MailingStreet!=c.MailingStreet){
				c.OtherStreet=c.MailingStreet;
				c.MailingStreet=oc.MailingStreet;
				c.OtherCity=c.MailingCity;
				c.MailingCity=oc.MailingCity;
				c.OtherState=c.MailingState;
				c.MailingState=oc.MailingState;
				c.OtherPostalCode=c.MailingPostalCode;
				c.MailingPostalCode=oc.MailingPostalCode;
				c.OtherCountry=c.MailingCountry;
				c.MailingCountry=oc.MailingCountry;
				c.OtherLatitude=c.MailingLatitude;
				c.MailingLatitude=oc.MailingLatitude;
				c.OtherLongitude=c.MailingLongitude;
				c.MailingLongitude=oc.MailingLongitude;
			}
      if(oc.mobilephone!=null){
        c.mobilephone=oc.mobilephone;
      }
      if(oc.otherphone!=null){
        c.otherphone=oc.otherphone;
      }
			if(oc.phone!=null && c.phone!=oc.phone){
        c.otherphone=c.phone;
        c.phone=oc.phone;
      }
      if(oc.salutation!=null){
        c.salutation=oc.salutation;
      }   
      if(oc.Survey_Flag__c!=null){
        c.Survey_Flag__c=oc.Survey_Flag__c;
      }  
      if(oc.title!=null){
        c.title=oc.title;
      }
    }
  } 
}